var data = {
    "publications":
    [
        // {
        //     "highlight": true,
        //     "img": "",
        //     "title": "",
        //     "authors": "",
        //     "conference": "",
        //     "year": ,
        //     "arxiv": "",
        //     "github": "",
        // },
        // Preprints
        
        {
            "highlight": true,
            "img": "images/compare2score.png",
            "title": "Adaptive Image Quality Assessment via Teaching Large Multimodal Model to Compare",
            "authors": "Hanwei Zhu*, Haoning Wu*, Yixuan Li, Zicheng Zhang, Baoliang Chen, Lingyu Zhu, Yuming Fang, Guangtao Zhai, Weisi Lin, Shiqi Wang",
            "preprint": "ArXiv preprint",
            "year": 2024,
            "project": "https://compare2score.github.io/",
            "arxiv": "https://arxiv.org/abs/2405.19298",
            "github": "https://github.com/h4nwei/Compare2Score",
        },
        {
            // "highlight": true,
            // "img": "images/gsr.jpg",
            "title": "Deep Shape-Texture Statistics for Completely Blind Image Quality Evaluation",
            "authors": "Yixuan Li, Peilin Chen, Hanwei Zhu, Keyan Ding, Leida Li, Shiqi Wang",
            "preprint": "ArXiv preprint",
            "year": 2024,
            "arxiv": "https://arxiv.org/pdf/2401.08107",
            // "github": "https://github.com/xiangjieSui/GSR",
        },
        {
            "highlight": true,
            "img": "images/gsr.jpg",
            "title": "Perceptual Quality Assessment of 360$\circ$ Images Based on Generative Scanpath Representation",
            "authors": "Xiangjie Sui*, Hanwei Zhu*, Xuelin Liu, Yuming Fang, Shiqi Wang, Zhou Wang",
            "preprint": "ArXiv preprint",
            "year": 2023,
            "arxiv": "https://arxiv.org/pdf/2309.03472",
            "github": "https://github.com/xiangjieSui/GSR",
        },
        {
            // "highlight": true,
            // "img": "images/gsr.jpg",
            "title": "Debiased Mapping for Full-Reference Image Quality Assessment",
            "authors": "Baoliang Chen, Hanwei Zhu, Lingyu Zhu, Shiqi Wang",
            "preprint": "ArXiv preprint",
            "year": 2023,
            "arxiv": "https://arxiv.org/pdf/2302.11464",
            // "github": "https://github.com/xiangjieSui/GSR",
        },
        {
            "highlight": true,
            "img": "images/deepdc.png",
            "title": "DeepDC: Deep Distance Correlation as a Perceptual Image Quality Evaluator",
            "authors": "Hanwei Zhu, Baoliang Chen, Lingyu Zhu, Shiqi Wang, Weisi Lin",
            "preprint": "ArXiv preprint",
            "year": 2023,
            "arxiv": "https://arxiv.org/abs/2211.04927",
            "github": "https://github.com/h4nwei/DeepDC",
        },
        // ========================================
        // Conference papers
        // ========================================
        {
            "highlight": true,
            "img": "images/co-instruct.png",
            "title": "Towards Open-ended Visual Quality Comparison",
            "authors": "Haoning Wu*, Hanwei Zhu*, Zicheng Zhang*, Erli Zhang, Chaofeng Chen, Liang Liao, Chunyi Li, Annan Wang, Wenxiu Sun, Qiong Yan, Xiaohong Liu, Guangtao Zhai, Shiqi Wang, Weisi Lin",
            "conference": "European Conference on Computer Vision (<b>ECCV</b>)",
            "year": 2024,
            "project": "https://co-instruct.github.io/",
            "arxiv": "https://arxiv.org/abs/2402.16641",
            "github": "https://github.com/Q-Future/Co-Instruct",
        },
        {
            "highlight": false,
            "img": "images/udu-net.png",
            "title": "Unrolled Decomposed Unpaired Learning for Controllable Low-Light Video Enhancement",
            "authors": "Lingyu Zhu, Wenhan Yang, Baoliang Chen, Hanwei Zhu, Zhangkai Ni, Qi Mao, Shiqi Wang",
            "conference": "European Conference on Computer Vision (<b>ECCV</b>)",
            "year": 2024,
            "arxiv": "https://arxiv.org/abs/tbd",
            "github": "https://github.com/tbd",
        },
        {
            "highlight": true,
            "img": "images/scandmm.jpg",
            "title": "ScanDMM: A Deep Markov Model of Scanpath Prediction for VR Images",
            "authors": "Xiangjie Sui, Yuming Fang, Hanwei Zhu, Shiqi Wang, Zhou Wang",
            "conference": "Computer Vision and Pattern Recognition (<b>CVPR</b>)",
            "year": 2023,
            "arxiv": "https://openaccess.thecvf.com/content/CVPR2023/papers/Sui_ScanDMM_A_Deep_Markov_Model_of_Scanpath_Prediction_for_360deg_CVPR_2023_paper.pdf",
            "github": "https://github.com/xiangjieSui/ScanDMM",
        },
        {
            "highlight": false,
            // "img": "images/deepwsd.jpg",
            "title": "DeepWSD: Projecting Degradations in Perceptual Space to Wasserstein Distance in Deep Feature Space",
            "authors": "Xingran Liao, Baoliang Chen, Hanwei Zhu, Shiqi Wang, Mingliang Zhou, Sam Kwong",
            "conference": "ACM International Conference on Multimedia (<b>MM</b>)",
            "year": 2022,
            "arxiv": "https://arxiv.org/pdf/2208.03323",
            "github": "https://github.com/Buka-Xing/DeepWSD",
        },
        {
            "highlight": true,
            "img": "images/spaq.jpg",
            "title": "Perceptual Quality Assessment of Smartphone Photography",
            "authors": "Yuming Fang*, Hanwei Zhu*, Yan Zeng, Kede Ma, Zhou Wang",
            "conference": "Computer Vision and Pattern Recognition (<b>CVPR</b>)",
            "year": 2020,
            "arxiv": "https://openaccess.thecvf.com/content_CVPR_2020/papers/Fang_Perceptual_Quality_Assessment_of_Smartphone_Photography_CVPR_2020_paper.pdf",
            "github": "https://github.com/h4nwei/SPAQ",
        },
        {
            // "img": "images/deepwsd.jpg",
            "title": "Image Quality Assessment of Multi-Exposure Image Fusion for Both Static and Dynamic Scenes",
            "authors": "Yuming Fang, Yan Zeng, Hanwei Zhu, Guangtao Zhai",
            "conference": "IEEE International Conference on Multimedia and Expo (<b>ICME</b>)",
            "year": 2019,
            "pdf": "https://ieeexplore.ieee.org/abstract/document/8784707/",
            // "github": "https://github.com/Buka-Xing/DeepWSD",
        },
        {
            // "img": "images/deepwsd.jpg",
            "title": "Perceptual Quality Assessment of HDR Deghosting Algorithms",
            "authors": "Yuming Fang, Hanwei Zhu, Kede Ma, Zhou Wang",
            "conference": "IEEE International Conference on Image Processing (<b>ICIP</b>)",
            "year": 2019,
            "pdf": "https://ece.uwaterloo.ca/~z70wang/publications/icip17a.pdf",
            // "github": "https://github.com/Buka-Xing/DeepWSD",
        },

        // ========================================
        // Journal papers
        // ========================================
        {
            "highlight": true,
            "img": "images/2afc-lmm.jpg",
            "title": "2AFC Prompting of Large Multimodal Models for Image Quality Assessment",
            "authors": "Hanwei Zhu*, Xiangjie Sui*, Baoliang Chen, Xulin Liu, Peilin Chen, Yuming Fang, Shiqi Wang",
            "journal": "IEEE Transactions on Circuits and Systems for Video Technology (<b>TCSVT</b>)",
            "year": 2024,
            "arxiv": "https://arxiv.org/abs/2402.01162",
            "github": "https://github.com/h4nwei/2AFC-LMMs",
        },
        {
            // "highlight": true,
            // "img": "images/stra-vqa.png",
            "title": "Temporally Consistent Enhancement of Low-Light Videos via Spatial-Temporal Compatible Learning",
            "authors": "Lingyu Zhu, Wenhan Yang, Baoliang Chen, Hanwei Zhu, Xiandong Meng, Shiqi Wang",
            "journal": "International Journal of Computer Vision (<b>IJCV</b>)",
            "year": 2024,
            "pdf": "https://link.springer.com/article/10.1007/s11263-024-02084-w",
            "github": "https://github.com/lingyzhu0101/low-light-video-enhancement",
        },
        {
            "highlight": true,
            "img": "images/dfss-iqa",
            "title": "Deep Feature Statistics Mapping for Generalized Screen Content Image Quality Assessment",
            "authors": "Baoliang Chen, Hanwei Zhu, Lingyu Zhu, Shiqi Wang, Sam Kwong",
            "journal": "IEEE Transactions on Image Processing (<b>TIP</b>)",
            "year": 2024,
            "arxiv": "https://arxiv.org/pdf/2209.05321",
            "github": "https://github.com/Baoliang93/DFSS-IQA",
        },
        {
            // "highlight": true,
            // "img": "images/stra-vqa.png",
            "title": "Gap-Closing Matters: Perceptual Quality Evaluation and Optimization of Low-Light Image Enhancement",
            "authors": "Baoliang Chen, Lingyu Zhu, Hanwei Zhu, Wenhan Yang, Linqi Song, Shiqi Wang",
            "journal": "IEEE Transactions on Multimedia (<b>TMM</b>)",
            "year": 2024,
            "arxiv": "https://arxiv.org/pdf/2302.11464",
            // "github": "https://github.com/Baoliang93/DFSS-IQA",
        },
        {
            "highlight": true,
            "img": "images/stra-vqa.png",
            "title": "Video Quality Assessment for Spatio-Temporal Resolution Adaptive Coding",
            "authors": "Hanwei Zhu, Baoliang Chen, Lingyu Zhu, Peilin Chen, Linqi Song, Shiqi Wang",
            "journal": "IEEE Transactions on Circuits and Systems for Video Technology (<b>TCSVT</b>)",
            "year": 2024,
            "pdf": "https://h4nwei.github.io/papers/23_TCSVT_STRA_VQA.pdf",
            "github": "https://github.com/h4nwei/STRA-VQA",
        },
        {
            // "highlight": true,
            // "img": "images/stra-vqa.png",
            "title": "No-Reference Image Quality Assessment by Hallucinating Pristine Features",
            "authors": "Baoliang Chen, Lingyu Zhu, Chenqi Kong, Hanwei Zhu, Shiqi Wang, Zhu Li",
            "journal": "IEEE Transactions on Image Processing (<b>TIP</b>)",
            "year": 2022,
            "arxiv": "https://arxiv.org/pdf/2108.04165",
            "github": "https://github.com/Baoliang93/FRP",
        },
        {
            "highlight": true,
            "img": "images/sti-vqa.png",
            "title": "Learning Spatiotemporal Interactions for User-Generated Video Quality Assessment",
            "authors": "Hanwei Zhu, Baoliang Chen, Lingyu Zhu, Shiqi Wang",
            "journal": "IEEE Transactions on Circuits and Systems for Video Technology (<b>TCSVT</b>)",
            "year": 2023,
            "pdf": "https://h4nwei.github.io/papers/22_TCSVT_STI_VQA.pdf",
            "github": "https://github.com/h4nwei/STI-VQA",
        },
        {
            // "highlight": true,
            // "img": "images/sti-vqa.png",
            "title": "Superpixel-Based Quality Assessment of Multi-Exposure Image Fusion for Both Static and Dynamic Scenes",
            "authors": "Yuming Fang, Yan Zeng, Wenhui Jiang, Hanwei Zhu, Jiebin Yan",
            "journal": "IEEE Transactions on Image Processing (<b>TIP</b>)",
            "year": 2023,
            "pdf": "https://ieeexplore.ieee.org/abstract/document/9337173/",
            // "github": "https://github.com/h4nwei/STI-VQA",
        },
        {
            "highlight": false,
            "img": "images/mefnet.png",
            "title": "Deep Guided Learning for Fast Multi-exposure Image Fusion",
            "authors": "Kede Ma, Zhengfang Duanmu, Hanwei Zhu, Yuming Fang, Zhou Wang",
            "journal": "IEEE Transactions on Image Processing (<b>TIP</b>)",
            "year": 2019,
            "pdf": "https://kedema.org/paper/19_TIP_MEF-Net.pdf",
            "github": "https://github.com/makedede/MEFNet",
        },
        {
            "highlight": true,
            "img": "images/mefssimd.jpg",
            "title": "Perceptual Evaluation for Multi-Exposure Image Fusion of Dynamic Scenes",
            "authors": "Yuming Fang, Hanwei Zhu, Kede Ma, Zhou Wang, Shutao Li",
            "journal": "IEEE Transactions on Image Processing (<b>TIP</b>)",
            "year": 2019,
            "pdf": "https://ece.uwaterloo.ca/~z70wang/publications/TIP_MEF-SSIMd.pdf",
            "github": "https://github.com/h4nwei/MEF-SSIMd",
        },

        
    ],
    "fields":
    {
        "arxiv": "arxiv",
        "pdf": "PDF",
        "github": "Github",
        "project": "Homepage",
    },
    "author_links":
    {
        "Shiqi Wang": "https://www.cs.cityu.edu.hk/~shiqwang/",
        "Baoliang Chen": "https://scholar.google.com/citations?hl=en&user=w_WL27oAAAAJ&view_op=list_works",
        "Lingyu Zhu": "https://scholar.google.com/citations?hl=en&user=IhyTEDkAAAAJ",
        "Chenqi Kong": "https://chenqikong.github.io/index.html",
        "Wenhan Yang": "https://flyywh.github.io/Publication.html",
        "Keyan Ding": "https://github.com/dingkeyan93",
        "Linqi Song": "https://sites.google.com/site/aisquaredlab/",
        "Sam Kwong": "https://scholars.ln.edu.hk/en/persons/sam-tak-wu-kwong",
        "Yuming Fang": "http://sim.jxufe.cn/JDMKL/ymfang_EN.html/",
        "Xiangjie Sui": "https://xiangjiesui.github.io/",
        "Xuelin Liu": "https://lxlhxl123.github.io/xuelin.github.com/",
        "Jiebin Yan": "http://sim.jxufe.edu.cn/down/show-37279.aspx?id=98",
        "Wenhui Jiang": "https://scholar.google.com/citations?hl=en&user=pAzm-UcAAAAJ&view_op=list_works&sortby=pubdate",
        "Kede Ma": "https://kedema.org//",
        "Zhengfang Duanmu": "https://ece.uwaterloo.ca/~zduanmu/",
        "Zhou Wang": "https://ece.uwaterloo.ca/~z70wang/",
        "Haoning Wu": "http://teowu.github.io/",
        "Chaofeng Chen": "https://chaofengc.github.io/",
        "Liang Liao": "https://liaoliang92.github.io/homepage/",
        "Weisi Lin": "https://personal.ntu.edu.sg/wslin/Home.html",
        "Leida Li": "https://web.xidian.edu.cn/ldli/en/index.html",
        "Chunyi Li": "http://lcysyzxdxc.github.io/",
        "Guangtao Zhai": "https://faculty.sjtu.edu.cn/zhaiguangtao/en/index.htm",
        "Zicheng Zhang": "https://github.com/zzc-1998",
        "Yipeng Qin": "https://www.cardiff.ac.uk/people/view/1508897-qin-yipeng",
        "Shaozheng Hao": "https://haoosz.github.io/",
        "Mengcheng Lan": "https://mc-lan.github.io/",
        "Wenxiu Sun": "http://wenxiusun.com/",
        "Weixia Zhang": "https://sites.google.com/view/r-panda",
        "Yixuan Gao": "https://github.com/YixuanGao98",
        "Annan Wang": "https://github.com/AnnanWangDaniel",
        "Erli Zhang": "https://github.com/ZhangErliCarl/",
        "Qiong Yan": "https://scholar.google.com/citations?user=uT9CtPYAAAAJ&hl=en",
        "Xiongkuo Min": "https://sites.google.com/site/minxiongkuo/",
        "Jingwen Hou": "https://scholar.google.com.sg/citations?user=NlNOyiQAAAAJ&hl=zh-CN",
        "Tao Yang": "https://github.com/yangxy",
        "Shihui Guo": "https://scholar.google.co.uk/citations?user=RPAVxiAAAAAJ&hl=en",
        "Xinyu Shi": "https://xinyu-shi.github.io/",
    }
};