var data = {
    "publications":
    [
        // {
        //     "highlight": false,
        //     "img": "",
        //     "title": "",
        //     "authors": "",
        //     "conference": "",
        //     "year": ,
        //     "arxiv": "",
        //     "github": "",
        // },
        // Preprints
        {
            "highlight": false,
            "title": "From Global to Granular: Revealing IQA Model Performance via Correlation Surface",
            "authors": "Baoliang Chen, Danni Huang, Hanwei Zhu, Lingyu Zhu, Wei Zhou, Shiqi Wang, Yuming Fang, Weisi Lin",
            "preprint": "ArXiv preprint",
            "year": 2026,
            "arxiv": "https://arxiv.org/abs/2601.21738",
        },
        {
            "highlight": false,
            "title": "Plug In, Grade Right: Psychology-Inspired AGIQA",
            "authors": "Zhicheng Liao, Baoliang Chen, Hanwei Zhu, Lingyu Zhu, Shiqi Wang, Weisi Lin",
            "preprint": "ArXiv preprint",
            "year": 2025,
            "arxiv": "https://arxiv.org/abs/2512.22780",
        },
        {
            "highlight": false,
            "title": "Benchmarking Corruption Robustness of LVLMs: A Discriminative Benchmark and Robustness Alignment Metric",
            "authors": "Xiangjie Sui, Songyang Li, Hanwei Zhu, Baoliang Chen, Yuming Fang, Xin Sun",
            "preprint": "ArXiv preprint",
            "year": 2025,
            "arxiv": "https://arxiv.org/abs/2511.19032",
        },
        {
            "highlight": false,
            "title": "AgenticIQA: An Agentic Framework for Adaptive and Interpretable Image Quality Assessment",
            "authors": "Hanwei Zhu, Yu Tian, Keyan Ding, Baoliang Chen, Bolin Chen, Shiqi Wang, Weisi Lin",
            "preprint": "ArXiv preprint",
            "year": 2025,
            "arxiv": "https://arxiv.org/pdf/2509.26006",
            "github": "https://agenticiqa.github.io/",
        },
        {
            "highlight": false,
            "title": "Pleno-Generation: A Scalable Generative Face Video Compression Framework with Bandwidth Intelligence",
            "authors": "Bolin Chen, Hanwei Zhu, Shanzhi Yin, Lingyu Zhu, Jie Chen, Ru-Ling Liao, Shiqi Wang, Yan Ye",
            "preprint": "ArXiv preprint",
            "year": 2025,
            "arxiv": "https://arxiv.org/pdf/2502.17085",
        },
        // ========================================
        // Conference papers
        // ========================================
        {
            "highlight": false,
            "title": "Modality-Aware Bit Allocation for Mixed-Precision Quantization of Vision-Language Models",
            "authors": "Xi Zhang, Hanwei Zhu, Jiamang Wang, Xiaolin Wu, Weisi Lin",
            "conference": "IEEE Computer Vision and Pattern Recognition Conference Findings (<b>CVPR</b>)",
            "year": 2026,
            "arxiv": "https://arxiv.org/pdf/2511.****",
        },
        {
            "highlight": false,
            "title": "Diversity Preserving Coresets for Image Quality Assessment",
            "authors": "Arpita Nema, Hanwei Zhu, Xi Zhang, Weisi Lin",
            "conference": "IEEE Winter Conference on Applications of Computer Vision (<b>WACV</b>)",
            "year": 2026,
            "arxiv": "https://openaccess.thecvf.com/content/WACV2026/papers/Nema_Diversity_Preserving_Coresets_for_Image_Quality_Assessment_WACV_2026_paper.pdf",
            "github": "https://github.com/Arpita2012/Q-Diversity",
        },
        {
            "highlight": false,
            "title": "Beyond Cosine Similarity: Magnitude-Aware CLIP for No-Reference Image Quality Assessment",
            "authors": "Zhicheng Liao, Dongxu Wu, Zhenshan Shi, Sijie Mai, Hanwei Zhu, Lingyu Zhu, Yuncheng Jiang, Baoliang Chen",
            "conference": "Annual AAAI Conference on Artificial Intelligence (<b>AAAI</b>)",
            "year": 2026,
            "arxiv": "https://arxiv.org/pdf/2511.09948",
            "github": "https://github.com/zhix000/MA-CLIP",
        },
        {
            "highlight": false,
            "title": "Mitigating perception bias: A training-free approach to enhance LMM for image quality assessment",
            "authors": "Baoliang Chen, Siyi Pan, Dongxu Wu, Liang Xie, Xiangjie Sui, Lingyu Zhu, Hanwei Zhu",
            "conference": "Annual AAAI Conference on Artificial Intelligence (<b>AAAI</b>)",
            "year": 2026,
            "arxiv": "https://arxiv.org/pdf/2411.12791",
            "github": "https://barrypan12138.github.io/Q-Debias/",
        },
        {
            "highlight": false,
            "title": "BADiff: Bandwidth Adaptive Diffusion Model",
            "authors": "Xi Zhang, Hanwei Zhu, Yan Zhong, Jiamang Wang, Weisi Lin",
            "conference": "Conference on Neural Information Processing Systems (<b>NeurIPS</b>)",
            "year": 2025,
            "arxiv": "https://arxiv.org/abs/2510.21366",
            "github": "https://github.com/xzhang9308/BADiff",
        },
        {
            "highlight": false,
            "title": "VQualA 2025 Challenge on Visual Quality Comparison for Large Multimodal Models: Methods and Results",
            "authors": "Hanwei Zhu, Haoning Wu, Zicheng Zhang, Lingyu Zhu, Yixuan Li, Peilin Chen, Shiqi Wang, Chris Wei Zhou, et al.",
            "conference": "IEEE/CVF International Conference on Computer Vision Workshop (<b>ICCV</b>)",
            "year": 2025,
            "pdf": "https://openaccess.thecvf.com/content/ICCV2025W/VQualA/papers/Zhu_VQualA_2025_Challenge_on_Visual_Quality_Comparison_for_Large_Multimodal_ICCVW_2025_paper.pdf",
            "project": "https://codalab.lisn.upsaclay.fr/competitions/23016",
        },
        {
            "highlight": false,
            "title": "Challenges in Governance of Harmful User Generated Content in Virtual Worlds",
            "authors": "Jeannie S Lee, Kan Chen, Raymond Chan, Xiaorong Li, Jisu Kim, Harminder Singh, Hanwei Zhu, Weisi Lin, Ming Di Koa, Mark McGill, Mohamed Khamis, Guo Freeman, Mark Billinghurst",
            "conference": "IEEE International Symposium on Mixed and Augmented Reality Adjunct (<b>ISMAR-Adjunct</b>)",
            "year": 2025,
            "pdf": "https://ieeexplore.ieee.org/abstract/document/11236224/",
        },
        {
            "highlight": false,
            "title": "Compressing Human Body Video with Interactive Semantics: A Generative Approach",
            "authors": "Bolin Chen, Shanzhi Yin, Hanwei Zhu, Lingyu Zhu, Zihan Zhang, Jie Chen, Ru-Ling Liao, Shiqi Wang, Yan Ye",
            "conference": "IEEE International Conference on Image Processing (<b>ICIP</b>)",
            "year": 2025,
            "arxiv": "https://arxiv.org/pdf/2505.16152?",
        },
        {
            "highlight": false,
            "title": "Holistic Coreset Selection for Data Efficient Image Quality Assessment",
            "authors": "Arpita Nema, Hanwei Zhu, Weisi Lin",
            "conference": "IEEE International Conference on Image Processing (<b>ICIP</b>)",
            "year": 2025,
            "pdf": "https://ieeexplore.ieee.org/abstract/document/11084586/",
        },
        {
            "highlight": false,
            "title": "AI-generated Image Quality Assessment in Visual Communication",
            "authors": "Yu Tian, Yixuan Li, Baoliang Chen, Hanwei Zhu, Shiqi Wang, Sam Kwong",
            "conference": "Annual AAAI Conference on Artificial Intelligence (<b>AAAI</b>)",
            "year": 2025,
            "arxiv": "https://arxiv.org/abs/2412.15677",
            "github": "https://github.com/ytian73/AIGI-VC",
        },
        {
            "highlight": false,
            "img": "images/compare2score.png",
            "title": "Adaptive Image Quality Assessment via Teaching Large Multimodal Model to Compare",
            "authors": "Hanwei Zhu, Haoning Wu, Yixuan Li, Zicheng Zhang, Baoliang Chen, Lingyu Zhu, Yuming Fang, Guangtao Zhai, Weisi Lin, Shiqi Wang",
            "conference": "Conference on Neural Information Processing Systems (<b>NeurIPS</b>)",
            "oral": "Spotlight",
            "year": 2024,
            "project": "https://compare2score.github.io/",
            "arxiv": "https://arxiv.org/abs/2405.19298",
            "github": "https://github.com/Q-Future/Compare2Score",
        },
        {
            "highlight": false,
            "img": "images/co-instruct.png",
            "title": "Towards Open-ended Visual Quality Comparison",
            "authors": "Haoning Wu*, Hanwei Zhu*, Zicheng Zhang*, Erli Zhang, Chaofeng Chen, Liang Liao, Chunyi Li, Annan Wang, Wenxiu Sun, Qiong Yan, Xiaohong Liu, Guangtao Zhai, Shiqi Wang, Weisi Lin",
            "conference": "European Conference on Computer Vision (<b>ECCV</b>)",
            "year": 2024,
            "oral": "Oral",
            "project": "https://co-instruct.github.io/",
            "arxiv": "https://arxiv.org/abs/2402.16641",
            "github": "https://github.com/Q-Future/Co-Instruct",
        },
        {
            "highlight": false,
            "img": "images/udu-net.png",
            "title": "Unrolled Decomposed Unpaired Learning for Controllable Low-Light Video Enhancement",
            "authors": "Lingyu Zhu, Wenhan Yang, Baoliang Chen, Hanwei Zhu, Zhangkai Ni, Qi Mao, Shiqi Wang",
            "conference": "European Conference on Computer Vision (<b>ECCV</b>)",
            "year": 2024,
            "arxiv": "https://arxiv.org/abs/tbd",
            "github": "https://github.com/tbd",
        },
        {
            "highlight": false,
            "img": "images/scandmm.jpg",
            "title": "ScanDMM: A Deep Markov Model of Scanpath Prediction for VR Images",
            "authors": "Xiangjie Sui, Yuming Fang, Hanwei Zhu, Shiqi Wang, Zhou Wang",
            "conference": "Computer Vision and Pattern Recognition (<b>CVPR</b>)",
            "year": 2023,
            "arxiv": "https://openaccess.thecvf.com/content/CVPR2023/papers/Sui_ScanDMM_A_Deep_Markov_Model_of_Scanpath_Prediction_for_360deg_CVPR_2023_paper.pdf",
            "github": "https://github.com/xiangjieSui/ScanDMM",
        },
        {
            "highlight": false,
            // "img": "images/deepwsd.jpg",
            "title": "DeepWSD: Projecting Degradations in Perceptual Space to Wasserstein Distance in Deep Feature Space",
            "authors": "Xingran Liao, Baoliang Chen, Hanwei Zhu, Shiqi Wang, Mingliang Zhou, Sam Kwong",
            "conference": "ACM International Conference on Multimedia (<b>MM</b>)",
            "year": 2022,
            "arxiv": "https://arxiv.org/pdf/2208.03323",
            "github": "https://github.com/Buka-Xing/DeepWSD",
        },
        {
            "highlight": false,
            "img": "images/spaq.jpg",
            "title": "Perceptual Quality Assessment of Smartphone Photography",
            "authors": "Yuming Fang*, Hanwei Zhu*, Yan Zeng, Kede Ma, Zhou Wang",
            "conference": "Computer Vision and Pattern Recognition (<b>CVPR</b>)",
            "year": 2020,
            "arxiv": "https://openaccess.thecvf.com/content_CVPR_2020/papers/Fang_Perceptual_Quality_Assessment_of_Smartphone_Photography_CVPR_2020_paper.pdf",
            "github": "https://github.com/h4nwei/SPAQ",
        },
        {
            // "img": "images/deepwsd.jpg",
            "title": "Image Quality Assessment of Multi-Exposure Image Fusion for Both Static and Dynamic Scenes",
            "authors": "Yuming Fang, Yan Zeng, Hanwei Zhu, Guangtao Zhai",
            "conference": "IEEE International Conference on Multimedia and Expo (<b>ICME</b>)",
            "year": 2019,
            "pdf": "https://ieeexplore.ieee.org/abstract/document/8784707/",
            // "github": "https://github.com/Buka-Xing/DeepWSD",
        },
        {
            // "img": "images/deepwsd.jpg",
            "title": "Perceptual Quality Assessment of HDR Deghosting Algorithms",
            "authors": "Yuming Fang, Hanwei Zhu, Kede Ma, Zhou Wang",
            "conference": "IEEE International Conference on Image Processing (<b>ICIP</b>)",
            "year": 2019,
            "pdf": "https://ece.uwaterloo.ca/~z70wang/publications/icip17a.pdf",
            // "github": "https://github.com/Buka-Xing/DeepWSD",
        },

        // ========================================
        // Journal papers
        // ========================================
        {
            "highlight": false,
            "img": "images/deepdc.png",
            "title": "DeepDC: Deep Distance Correlation as a Perceptual Image Quality Evaluator",
            "authors": "Hanwei Zhu, Baoliang Chen, Lingyu Zhu, Shiqi Wang, Weisi Lin",
            "journal": "IEEE Transactions on Image Processing (<b>TIP</b>)",
            "year": 2025,
            "arxiv": "https://arxiv.org/abs/2211.04927",
            "github": "https://github.com/h4nwei/DeepDC",
        },
        {
            "highlight": false,
            "img": "images/gsr.jpg",
            "title": "Perceptual Quality Assessment of 360 Images Based on Generative Scanpath Representation",
            "authors": "Xiangjie Sui*, Hanwei Zhu*, Xuelin Liu, Yuming Fang, Shiqi Wang, Zhou Wang",
            "journal": "IEEE Transactions on Image Processing (<b>TIP</b>)",
            "year": 2025,
            "arxiv": "https://arxiv.org/pdf/2309.03472",
            "github": "https://github.com/xiangjieSui/GSR",
        },
        {
            "highlight": false,
            "img": "images/debiased.png",
            "title": "Debiased Mapping for Full-Reference Image Quality Assessment",
            "authors": "Baoliang Chen, Hanwei Zhu, Lingyu Zhu, Shiqi Wang",
            "journal": "IEEE Transactions on Multimedia (<b>TMM</b>)",
            "year": 2024,
            "arxiv": "https://arxiv.org/pdf/2302.11464v1",
            "github": "https://github.com/Baoliang93/DMM",
        },
        {
            // "highlight": false,
            // "img": "images/gsr.jpg",
            "title": "Deep Shape-Texture Statistics for Completely Blind Image Quality Evaluation",
            "authors": "Yixuan Li, Peilin Chen, Hanwei Zhu, Keyan Ding, Leida Li, Shiqi Wang",
            "year": 2024,
            "journal": "ACM Transactions on Multimedia Computing, Communications, and Applications (<b>ToMM</b>)",
            "arxiv": "https://arxiv.org/pdf/2401.08107",
            // "github": "https://github.com/xiangjieSui/GSR",
        },
        {
            "highlight": false,
            "img": "images/2afc-lmm.jpg",
            "title": "2AFC Prompting of Large Multimodal Models for Image Quality Assessment",
            "authors": "Hanwei Zhu*, Xiangjie Sui*, Baoliang Chen, Xulin Liu, Peilin Chen, Yuming Fang, Shiqi Wang",
            "journal": "IEEE Transactions on Circuits and Systems for Video Technology (<b>TCSVT</b>)",
            "year": 2024,
            "arxiv": "https://arxiv.org/abs/2402.01162",
            "github": "https://github.com/h4nwei/2AFC-LMMs",
        },
        {
            // "highlight": false,
            // "img": "images/stra-vqa.png",
            "title": "Temporally Consistent Enhancement of Low-Light Videos via Spatial-Temporal Compatible Learning",
            "authors": "Lingyu Zhu, Wenhan Yang, Baoliang Chen, Hanwei Zhu, Xiandong Meng, Shiqi Wang",
            "journal": "International Journal of Computer Vision (<b>IJCV</b>)",
            "year": 2024,
            "pdf": "https://link.springer.com/article/10.1007/s11263-024-02084-w",
            "github": "https://github.com/lingyzhu0101/low-light-video-enhancement",
        },
        {
            "highlight": false,
            "img": "images/dfss-iqa.png",
            "title": "Deep Feature Statistics Mapping for Generalized Screen Content Image Quality Assessment",
            "authors": "Baoliang Chen, Hanwei Zhu, Lingyu Zhu, Shiqi Wang, Sam Kwong",
            "journal": "IEEE Transactions on Image Processing (<b>TIP</b>)",
            "year": 2024,
            "arxiv": "https://arxiv.org/pdf/2209.05321",
            "github": "https://github.com/Baoliang93/DFSS-IQA",
        },
        {
            // "highlight": false,
            // "img": "images/stra-vqa.png",
            "title": "Gap-Closing Matters: Perceptual Quality Evaluation and Optimization of Low-Light Image Enhancement",
            "authors": "Baoliang Chen, Lingyu Zhu, Hanwei Zhu, Wenhan Yang, Linqi Song, Shiqi Wang",
            "journal": "IEEE Transactions on Multimedia (<b>TMM</b>)",
            "year": 2024,
            "arxiv": "https://arxiv.org/pdf/2302.11464",
            "github": "https://github.com/Baoliang93/IACA_For_Lowlight_IQA",
        },
        {
            "highlight": false,
            "img": "images/stra-vqa.png",
            "title": "Video Quality Assessment for Spatio-Temporal Resolution Adaptive Coding",
            "authors": "Hanwei Zhu, Baoliang Chen, Lingyu Zhu, Peilin Chen, Linqi Song, Shiqi Wang",
            "journal": "IEEE Transactions on Circuits and Systems for Video Technology (<b>TCSVT</b>)",
            "year": 2024,
            "pdf": "https://h4nwei.github.io/papers/23_TCSVT_STRA_VQA.pdf",
            "github": "https://github.com/h4nwei/STRA-VQA",
        },
        {
            // "highlight": false,
            // "img": "images/stra-vqa.png",
            "title": "No-Reference Image Quality Assessment by Hallucinating Pristine Features",
            "authors": "Baoliang Chen, Lingyu Zhu, Chenqi Kong, Hanwei Zhu, Shiqi Wang, Zhu Li",
            "journal": "IEEE Transactions on Image Processing (<b>TIP</b>)",
            "year": 2022,
            "arxiv": "https://arxiv.org/pdf/2108.04165",
            "github": "https://github.com/Baoliang93/FRP",
        },
        {
            "highlight": false,
            "img": "images/sti-vqa.png",
            "title": "Learning Spatiotemporal Interactions for User-Generated Video Quality Assessment",
            "authors": "Hanwei Zhu, Baoliang Chen, Lingyu Zhu, Shiqi Wang",
            "journal": "IEEE Transactions on Circuits and Systems for Video Technology (<b>TCSVT</b>)",
            "year": 2023,
            "pdf": "https://h4nwei.github.io/papers/22_TCSVT_STI_VQA.pdf",
            "github": "https://github.com/h4nwei/STI-VQA",
        },
        {
            // "highlight": false,
            // "img": "images/sti-vqa.png",
            "title": "Superpixel-Based Quality Assessment of Multi-Exposure Image Fusion for Both Static and Dynamic Scenes",
            "authors": "Yuming Fang, Yan Zeng, Wenhui Jiang, Hanwei Zhu, Jiebin Yan",
            "journal": "IEEE Transactions on Image Processing (<b>TIP</b>)",
            "year": 2021,
            "pdf": "https://ieeexplore.ieee.org/abstract/document/9337173/",
            // "github": "https://github.com/h4nwei/STI-VQA",
        },
        {
            "highlight": false,
            "img": "images/mefnet.png",
            "title": "Deep Guided Learning for Fast Multi-exposure Image Fusion",
            "authors": "Kede Ma, Zhengfang Duanmu, Hanwei Zhu, Yuming Fang, Zhou Wang",
            "journal": "IEEE Transactions on Image Processing (<b>TIP</b>)",
            "year": 2019,
            "pdf": "https://kedema.org/paper/19_TIP_MEF-Net.pdf",
            "github": "https://github.com/makedede/MEFNet",
        },
        {
            "highlight": false,
            "img": "images/mefssimd.jpg",
            "title": "Perceptual Evaluation for Multi-Exposure Image Fusion of Dynamic Scenes",
            "authors": "Yuming Fang, Hanwei Zhu, Kede Ma, Zhou Wang, Shutao Li",
            "journal": "IEEE Transactions on Image Processing (<b>TIP</b>)",
            "year": 2019,
            "pdf": "https://ece.uwaterloo.ca/~z70wang/publications/TIP_MEF-SSIMd.pdf",
            "github": "https://github.com/h4nwei/MEF-SSIMd",
        },

        
    ],
    "fields":
    {
        "arxiv": "arxiv",
        "pdf": "PDF",
        "github": "Github",
        "project": "Homepage",
    },
};